"""empty message

Revision ID: 19c280503028
Revises: 
Create Date: 2019-08-09 13:50:06.727736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c280503028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fueltype', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.String(length=50), nullable=False),
    sa.Column('assessor', sa.String(length=50), nullable=False),
    sa.Column('approver', sa.String(length=50), nullable=False),
    sa.Column('plusvehicle', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('requestedBy', sa.Integer(), nullable=True),
    sa.Column('daterequired', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestId', sa.Integer(), nullable=False),
    sa.Column('respondentId', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('responses')
    op.drop_table('fuel')
    # ### end Alembic commands ###
