"""empty message

Revision ID: 21b72aa116ca
Revises: fea8c3e2a2f8
Create Date: 2020-05-23 20:21:10.130808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b72aa116ca'
down_revision = 'fea8c3e2a2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('experience_needed', sa.String(length=50), nullable=False),
    sa.Column('skills_needed', sa.String(length=50), nullable=False),
    sa.Column('education_needed', sa.String(length=50), nullable=False),
    sa.Column('ad_starts', sa.String(length=50), nullable=False),
    sa.Column('ad_ends', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.Column('employer_email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('employer')
    # ### end Alembic commands ###
