"""empty message

Revision ID: 546b87b24ed1
Revises: a1c4fba40800
Create Date: 2020-05-25 11:13:21.438009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '546b87b24ed1'
down_revision = 'a1c4fba40800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('applicatant_id', sa.Integer(), nullable=True),
    sa.Column('application_score', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('person', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'person', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.alter_column('person', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_table('applications')
    # ### end Alembic commands ###
