"""empty message

Revision ID: 9ff5f5e8b868
Revises: 5b08226c2e33
Create Date: 2020-03-14 18:05:17.610577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ff5f5e8b868'
down_revision = '5b08226c2e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'createdBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdBy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'fullname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
