"""empty message

Revision ID: a1c4fba40800
Revises: 21b72aa116ca
Create Date: 2020-05-24 13:05:38.329828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1c4fba40800'
down_revision = '21b72aa116ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='employer')
    op.drop_column('employer', 'password')
    op.drop_column('employer', 'email')
    op.drop_column('employer', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer', sa.Column('fullname', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('employer', sa.Column('email', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('employer', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('email', 'employer', ['email'], unique=True)
    # ### end Alembic commands ###
