"""empty message

Revision ID: ec492bd18db6
Revises: cdcb49b46ca6
Create Date: 2020-04-24 18:04:44.311482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec492bd18db6'
down_revision = 'cdcb49b46ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currently', table_name='experience')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('currently', 'experience', ['currently'], unique=True)
    # ### end Alembic commands ###
